### ISSUE TITLE
AuthenticationState.authenticated gives false

### ISSUE THREAD

**Issue by javialej87** [jnt0r/vue-auth0-plugin#324]
AuthenticationState.authenticated gives "false" in JS files which don't have access to the Vue instance even though accessing auth from the "injected" module shows the correct user.

**Comment by jnt0r** [comment]
Hey @javialej87, thank you for your issue.

Maybe the code in your js file is executed before the authentication state is determined and set in the plugin. Do you still see this behavior if you delay the execution in your js file?

Do you have a repository or a simple project where I can reproduce the problem?

**Comment by danielnice** [comment]
I have found this issue as well because I want to use the AuthenticationState in my router setup to redirects users differently based on auth state.  It is exactly like @jnt0r said, the state is still loading when I am pulling it, perhaps there would be a way to return the AuthState in a promise or else make it so you can use the AuthenticationGaurd function without calling the automatic login redirect?  I am looking to do something like this:

`router.beforeEach(async (to, from, next) => {
  log.debug(from, to, AuthenticationState);
  if (to.name === "XYZ") {
    const authed = await AuthenticationState.authenticated;
    if (authed) {
      next("/authed-landing");
    } else {
      next();
    }
  } else {
    next();
  }
});`

**Comment by jnt0r** [comment]
Hey @danielnice, thanks for your comment on this. I like your idea of making the authenticated Property a Promise. I need to think about whether there is an Issue involving this change. I think this would change the current behavior of the authenticated Property.

**Comment by jnt0r** [comment]
Preparing this in #371

**Comment by javier-sanchez-cj** [comment]
sorry for not answering this!! Although i been following the whole conversation. The problem was exactly as @danielnice commented. I'm using Quasar which uses boot files (is a bit different from other frameworks like Vuetify) and i believe that it's the order in which things are executed.

Looking forward to the #371   !!

great work @jnt0r

**Comment by javialej87** [comment]
sorry for not answering this!! Although i been following the whole conversation. The problem was exactly as @danielnice commented. I'm using Quasar which uses boot files (is a bit different from other frameworks like Vuetify) and i believe that it's the order in which things are executed.

Looking forward to the #371  !!

great work @jnt0r

**Comment by jnt0r** [comment]
I just released the beta version [v2.6.0-beta.1](https://github.com/jnt0r/vue-auth0-plugin/releases/tag/v2.6.0-beta.1) including these features.
Can you test it out if it finds your needs?

**Comment by danielnice** [comment]
> I just released the beta version [v2.6.0-beta.1](https://github.com/jnt0r/vue-auth0-plugin/releases/tag/v2.6.0-beta.1) including these features. Can you test it out if it finds your needs?

I will take a look when I get a chance here soon, thanks!

**Comment by jnt0r** [comment]
Hey @danielnice, did you try the beta version yet?

**Comment by jnt0r** [comment]
Thanks for your feedback, @danielnice. Yes, the function name is long, but at least it exactly says what it does ;)
